name: CI Tests

on: [ pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "requirements.txt" 

      - name: Set up Python
        run: uv python install 3.12

      - name: Install Dependencies
        run: uv pip install --system -r requirements.txt

      - name: Run Tests
        env:
          PINECONE_API_KEY: "test-key"
          SERPAPI_API_KEY: "test-key"
        run: pytest tests/